# Use the official Prefect image
FROM prefecthq/prefect:3-latest

# Expose Prefect Server port for communication
EXPOSE 4200

# Start the Prefect server on port 4200 and listen on all interfaces
CMD prefect server start --host 0.0.0.0 --port 4200

