version: '3.8'

services:
  prefect-server:
    image: prefecthq/prefect:2-latest
    ports:
      - "4200:4200"
    command: prefect server start --host 0.0.0.0

  pipeline:
    build: .
    volumes:
      - .:/app
    depends_on:
      - prefect-server
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
    command: python pipeline.py