version: '3'
services:
  # Your Python application
  my-python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Expose the port your app uses
    depends_on:
      - prefect-server
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api/  # Point to the Prefect server
    networks:
      - prefect-net
    restart: always

  # Prefect Server
  prefect-server:
    image: prefecthq/prefect:latest
    ports:
      - "4200:4200"
    #volumes:
   #   - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket for DinD
    command: prefect server start
    networks:
      - prefect-net
    build:
      context: .
      dockerfile: Dockerfile.prefect-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4200/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
# Top-level networks definition
networks:
  prefect-net:
    driver: bridge



